export async function register() {
  if (process.env.NEXT_RUNTIME === 'nodejs' && process.env.NEXT_PHASE !== 'phase-production-build') {
    const { ensureLeadershipGroupSync } = await import('./lib/leadership-groups-server')
    ensureLeadershipGroupSync()
    const { ensureClipCompressionWorker } = await import('./lib/clip-compression')
    ensureClipCompressionWorker()
    const { ensurePhotoCatalogSync } = await import('./lib/investigation-photos')
    ensurePhotoCatalogSync()
    const { ensureHirePingCleanup } = await import('./lib/hire-ping')
    ensureHirePingCleanup()
    const { ensureUploadCleanupWorker } = await import('./lib/upload-sessions')
    ensureUploadCleanupWorker()
    const { ensureManualDutyWorker } = await import('./lib/manual-duty')
    ensureManualDutyWorker()
    const { ensureDiscordGateway } = await import('./lib/discord-gateway')
    ensureDiscordGateway()
    const { ensureAgentStatusAutomationWorker } = await import('./lib/absence-status')
    ensureAgentStatusAutomationWorker()
    const [{ ensureDatabaseBackupScheduler }, { prisma }] = await Promise.all([import('./lib/database-backup'), import('./lib/prisma')])
    ensureDatabaseBackupScheduler(prisma)
    const { migrateContractSignatures } = await import('./lib/contract-signature-migration')
    void migrateContractSignatures()
      .then((count) => { if (count > 0) console.log(`[Contracts] ${count} fehlende Unterschriftszeilen angelegt`) })
      .catch((error) => console.error('[Contracts] Unterschriftszeilen konnten nicht angelegt werden:', error))
  }
}
